final Map<String, dynamic> diagnosisExercises = {
  "Mechanical Low Back Pain": [
    {
      "name": "Glute Bridges",
      "image": "assets/Exercises/glute bridges.png",
      "whatItHelps": "Strengthens glutes to reduce stress on the lower back.",
      "steps": [
        "Lie on your back, knees bent, feet hip-width apart",
        "Tighten your core and squeeze your glutes",
        "Lift hips until shoulders–hips–knees align",
        "Lower slowly",
      ],
      "reps": "10–12",
      "sets": "2–3",
    },
    {
      "name": "Side Plank Holds",
      "image": "assets/Exercises/side plank.png",
      "whatItHelps": "Builds lateral core strength for spinal stability.",
      "steps": [
        "Lie on your side, elbow under shoulder",
        "Bend knees (easier) or straighten legs",
        "Lift hips to form a straight line",
        "Hold and breathe",
      ],
      "reps": "Hold 15–30 sec",
      "sets": "2 per side",
    },
    {
      "name": "Bird Dog",
      "image": "assets/Exercises/bird dog.png",
      "whatItHelps": "Improves core control and spinal stability.",
      "steps": [
        "Start on hands and knees",
        "Extend opposite arm and leg",
        "Keep hips and spine stable",
        "Return and switch sides",
      ],
      "reps": "8–10 per side",
      "sets": "2",
    },
    {
      "name": "Squats",
      "image": "assets/Exercises/squats.png",
      "whatItHelps": "Strengthens legs and supports proper movement patterns.",
      "steps": [
        "Stand feet shoulder-width apart",
        "Sit back like a chair",
        "Keep chest upright and core engaged",
        "Stand back up",
      ],
      "reps": "8–12",
      "sets": "2",
    },
    {
      "name": "Dead Bug",
      "image": "assets/Exercises/dead bug.png",
      "whatItHelps": "Builds deep core stability without stressing the spine.",
      "steps": [
        "Lie on back, arms and legs raised",
        "Lower opposite arm and leg",
        "Keep lower back pressed into floor",
        "Return and switch sides",
      ],
      "reps": "8–10 per side",
      "sets": "2",
    },
  ],

  "Mechanical Mid Back Pain": [
    {
      "name": "Cat–Cow Pose",
      "image": "assets/Exercises/cat cow pose.png",
      "whatItHelps": "Improves spinal flexibility and reduces stiffness.",
      "steps": [
        "Hands under shoulders, knees under hips",
        "Arch back (cow)",
        "Round spine (cat)",
        "Move slowly with breathing",
      ],
      "reps": "8–10 cycles",
      "sets": "1–2",
    },
    {
      "name": "Thoracic Rotation Stretch",
      "image": "assets/Exercises/Thoracic Rotation Stretch.png",
      "whatItHelps": "Restores upper-back rotation.",
      "steps": [
        "Lie on side, knees bent",
        "Extend arms forward",
        "Open top arm across body",
        "Follow with your eyes",
      ],
      "reps": "6–8 per side",
      "sets": "2",
    },
    {
      "name": "Doorway Chest-Opening Stretch",
      "image": "assets/Exercises/Doorway Chest-Opening Stretch.png",
      "whatItHelps": "Opens chest and relieves upper-back tightness.",
      "steps": [
        "Place forearms on doorway",
        "Step forward gently",
        "Feel stretch across chest",
        "Hold and breathe",
      ],
      "reps": "Hold 20–30 sec",
      "sets": "2–3",
    },
    {
      "name": "Scapular Retraction (Band Pulls)",
      "image": "assets/Exercises/Scapular Retraction ( Band Pulls).png",
      "whatItHelps": "Strengthens upper-back muscles for posture.",
      "steps": [
        "Hold band at chest height",
        "Pull band apart",
        "Squeeze shoulder blades",
        "Slowly release",
      ],
      "reps": "10–15",
      "sets": "2",
    },
    {
      "name": "Foam Roller Thoracic Extension",
      "image": "assets/Exercises/Foam Roller Thoracic Extension.png",
      "whatItHelps": "Improves thoracic extension and posture.",
      "steps": [
        "Place roller under upper back",
        "Support head and neck",
        "Gently extend over roller",
        "Return slowly",
      ],
      "reps": "8–10",
      "sets": "1–2",
    },
  ],

  "Mechanical Upper Back Pain": [
    {
      "name": "Thoracic Extension on Chair",
      "image": "assets/Exercises/Thoracic Extension on Chair.png",
      "whatItHelps": "Counteracts slouched posture.",
      "steps": [
        "Sit upright on chair",
        "Hands behind head",
        "Extend upper back over chair",
        "Return to neutral",
      ],
      "reps": "8–10",
      "sets": "2",
    },
    {
      "name": "Scapular Retraction (Band Pulls)",
      "image": "assets/Exercises/Scapular Retraction ( Band Pulls).png",
      "whatItHelps": "Strengthens upper-back muscles for posture.",
      "steps": [
        "Hold band at chest height",
        "Pull band apart",
        "Squeeze shoulder blades",
        "Slowly release",
      ],
      "reps": "10–15",
      "sets": "2",
    },
    {
      "name": "Thoracic Rotation Stretch",
      "image": "assets/Exercises/Thoracic Rotation Stretch.png",
      "whatItHelps": "Improves upper-back mobility.",
      "steps": [
        "On hands and knees",
        "Slide one arm under body",
        "Rotate upper back",
        "Return and switch",
      ],
      "reps": "6–8 per side",
      "sets": "2",
    },
    {
      "name": "Doorway Chest-Opening Stretch",
      "image": "assets/Exercises/Doorway Chest-Opening Stretch.png",
      "whatItHelps": "Reduces rounded shoulders and tension.",
      "steps": [
        "Hands on doorway frame",
        "Step back slightly",
        "Lean chest forward",
        "Hold comfortably",
      ],
      "reps": "Hold 20–30 sec",
      "sets": "2–3",
    },
    {
      "name": "Prone Cobra",
      "image": "assets/Exercises/prone cobra.png",
      "whatItHelps": "Strengthens spinal extensors and improves posture.",
      "steps": [
        "Lie face down",
        "Lift chest slightly",
        "Squeeze shoulder blades",
        "Hold briefly",
      ],
      "reps": "Hold 5–10 sec",
      "sets": "6–8 reps",
    },
  ],

  "Mechanical Cervical / Neck Pain": [
    {
      "name": "Chin Tucks (Cervical Retraction)",
      "image": "assets/Exercises/Chin Tucks (Cervical Retraction).png",
      "whatItHelps": "Corrects forward head posture.",
      "steps": [
        "Sit upright",
        "Pull chin straight back",
        "Keep eyes forward",
        "Hold briefly",
      ],
      "reps": "8–10",
      "sets": "2",
    },
    {
      "name": "Neck Rotation & Side-Tilt Stretches",
      "image": "assets/Exercises/Neck Rotation & Side-Tilt Stretches.png",
      "whatItHelps": "Relieves neck stiffness.",
      "steps": [
        "Slowly turn head side to side",
        "Tilt ear toward shoulder",
        "Hold gently",
        "Switch sides",
      ],
      "reps": "Hold 15–20 sec",
      "sets": "2 per direction",
    },
    {
      "name": "Side Neck Isometric Holds",
      "image": "assets/Exercises/Side Neck Isometric Holds.png",
      "whatItHelps": "Strengthens neck muscles safely.",
      "steps": [
        "Place hand on side of head",
        "Gently press into hand",
        "Resist without moving",
        "Hold and release",
      ],
      "reps": "Hold 5–8 sec",
      "sets": "5 per side",
    },
    {
      "name": "Shoulder Blade Squeezes",
      "image": "assets/Exercises/Scapular Retraction _ Shoulder Blade Squeezes.png",
      "whatItHelps": "Activates postural muscles.",
      "steps": [
        "Sit or stand tall",
        "Pull shoulder blades together",
        "Hold briefly",
        "Relax",
      ],
      "reps": "10-12",
      "sets": "2",
    },
    {
      "name": "Doorway Chest-Opening Stretch",
      "image": "assets/Exercises/Doorway Chest-Opening Stretch.png",
      "whatItHelps": "Opens chest and relieves upper-back tightness.",
      "steps": [
        "Place forearms on doorway",
        "Step forward gently",
        "Feel stretch across chest",
        "Hold and breathe",
      ],
      "reps": "Hold 20–30 sec",
      "sets": "2–3",
    },
  ],
};

final List<Map<String, dynamic>> allExercises = [
  {
    "name": "Glute Bridges",
    "image": "assets/Exercises/glute bridges.png",
    "whatItHelps": "Strengthens glutes to reduce stress on the lower back.",
    "steps": [
      "Lie on your back, knees bent, feet hip-width apart",
      "Tighten your core and squeeze your glutes",
      "Lift hips until shoulders–hips–knees align",
      "Lower slowly",
    ],
    "reps": "10–12",
    "sets": "2–3",
  },
  {
    "name": "Side Plank Holds",
    "image": "assets/Exercises/side plank.png",
    "whatItHelps": "Builds lateral core strength for spinal stability.",
    "steps": [
      "Lie on your side, elbow under shoulder",
      "Bend knees (easier) or straighten legs",
      "Lift hips to form a straight line",
      "Hold and breathe",
    ],
    "reps": "Hold 15–30 sec",
    "sets": "2 per side",
  },
  {
    "name": "Bird Dog",
    "image": "assets/Exercises/bird dog.png",
    "whatItHelps": "Improves core control and spinal stability.",
    "steps": [
      "Start on hands and knees",
      "Extend opposite arm and leg",
      "Keep hips and spine stable",
      "Return and switch sides",
    ],
    "reps": "8–10 per side",
    "sets": "2",
  },
  {
    "name": "Squats",
    "image": "assets/Exercises/squats.png",
    "whatItHelps": "Strengthens legs and supports proper movement patterns.",
    "steps": [
      "Stand feet shoulder-width apart",
      "Sit back like a chair",
      "Keep chest upright and core engaged",
      "Stand back up",
    ],
    "reps": "8–12",
    "sets": "2",
  },
  {
    "name": "Dead Bug",
    "image": "assets/Exercises/dead bug.png",
    "whatItHelps": "Builds deep core stability without stressing the spine.",
    "steps": [
      "Lie on back, arms and legs raised",
      "Lower opposite arm and leg",
      "Keep lower back pressed into floor",
      "Return and switch sides",
    ],
    "reps": "8–10 per side",
    "sets": "2",
  },
  {
    "name": "Cat–Cow Pose",
    "image": "assets/Exercises/cat cow pose.png",
    "whatItHelps": "Improves spinal flexibility and reduces stiffness.",
    "steps": [
      "Hands under shoulders, knees under hips",
      "Arch back (cow)",
      "Round spine (cat)",
      "Move slowly with breathing",
    ],
    "reps": "8–10 cycles",
    "sets": "1–2",
  },
  {
    "name": "Thoracic Rotation Stretch",
    "image": "assets/Exercises/Thoracic Rotation Stretch.png",
    "whatItHelps": "Improves upper-back mobility and rotation.",
    "steps": [
      "Lie on side or start on hands and knees",
      "Rotate upper back",
      "Follow movement with eyes",
      "Return and switch sides",
    ],
    "reps": "6–8 per side",
    "sets": "2",
  },
  {
    "name": "Doorway Chest-Opening Stretch",
    "image": "assets/Exercises/Doorway Chest-Opening Stretch.png",
    "whatItHelps": "Opens chest and relieves upper-back tightness.",
    "steps": [
      "Place forearms on doorway",
      "Step forward gently",
      "Feel stretch across chest",
      "Hold and breathe",
    ],
    "reps": "Hold 20–30 sec",
    "sets": "2–3",
  },
  {
    "name": "Scapular Retraction (Band Pulls)",
    "image": "assets/Exercises/Scapular Retraction ( Band Pulls).png",
    "whatItHelps": "Strengthens upper-back muscles for posture.",
    "steps": [
      "Hold band at chest height",
      "Pull band apart",
      "Squeeze shoulder blades",
      "Slowly release",
    ],
    "reps": "10–15",
    "sets": "2",
  },
  {
    "name": "Foam Roller Thoracic Extension",
    "image": "assets/Exercises/Foam Roller Thoracic Extension.png",
    "whatItHelps": "Improves thoracic extension and posture.",
    "steps": [
      "Place roller under upper back",
      "Support head and neck",
      "Gently extend over roller",
      "Return slowly",
    ],
    "reps": "8–10",
    "sets": "1–2",
  },
  {
    "name": "Thoracic Extension on Chair",
    "image": "assets/Exercises/Thoracic Extension on Chair.png",
    "whatItHelps": "Counteracts slouched posture.",
    "steps": [
      "Sit upright on chair",
      "Hands behind head",
      "Extend upper back over chair",
      "Return to neutral",
    ],
    "reps": "8–10",
    "sets": "2",
  },
  {
    "name": "Prone Cobra",
    "image": "assets/Exercises/prone cobra.png",
    "whatItHelps": "Strengthens spinal extensors and improves posture.",
    "steps": [
      "Lie face down",
      "Lift chest slightly",
      "Squeeze shoulder blades",
      "Hold briefly",
    ],
    "reps": "Hold 5–10 sec",
    "sets": "6–8 reps",
  },
  {
    "name": "Chin Tucks (Cervical Retraction)",
    "image": "assets/Exercises/Chin Tucks (Cervical Retraction).png",
    "whatItHelps": "Corrects forward head posture.",
    "steps": [
      "Sit upright",
      "Pull chin straight back",
      "Keep eyes forward",
      "Hold briefly",
    ],
    "reps": "8–10",
    "sets": "2",
  },
  {
    "name": "Neck Rotation & Side-Tilt Stretches",
    "image": "assets/Exercises/Neck Rotation & Side-Tilt Stretches.png",
    "whatItHelps": "Relieves neck stiffness.",
    "steps": [
      "Slowly turn head side to side",
      "Tilt ear toward shoulder",
      "Hold gently",
      "Switch sides",
    ],
    "reps": "Hold 15–20 sec",
    "sets": "2 per direction",
  },
  {
    "name": "Side Neck Isometric Holds",
    "image": "assets/Exercises/Side Neck Isometric Holds.png",
    "whatItHelps": "Strengthens neck muscles safely.",
    "steps": [
      "Place hand on side of head",
      "Gently press into hand",
      "Resist without moving",
      "Hold and release",
    ],
    "reps": "Hold 5–8 sec",
    "sets": "5 per side",
  },
  {
    "name": "Shoulder Blade Squeezes",
    "image": "assets/Exercises/Scapular Retraction _ Shoulder Blade Squeezes.png",
    "whatItHelps": "Activates postural muscles.",
    "steps": [
      "Sit or stand tall",
      "Pull shoulder blades together",
      "Hold briefly",
      "Relax",
    ],
    "reps": "10–12",
    "sets": "2",
  },
];
